import 'dart:convert';

import 'package:flutter/cupertino.dart';

import '../singletons.dart';

class ChatUser
{
  /// Uid generated by Supabase. Only value is ''.
  final String uid;
  /// Name of user.
  final String name;
  /// Email address of user.
  final String email;
  /// Signature of user. If not provided default is ''.
  final String signature;
  /// Image of Url, if not provided a default will be used.
  final String avatarUrl;
  /// Date of creation
  final DateTime dateCreated;
  /// NEW: List of uids as contacts. Starts with null.
  final List<String> contacts;

  ChatUser({
    required this.uid,
    required this.name,
    required this.email,
    required this.signature,
    required this.avatarUrl,
    required this.dateCreated,
    required this.contacts
  });

  /// Converts a ChatUser2 object to a Map.
  Map<String, dynamic> toMap() {
    return {
      //'uid': uid,
      'name': name,
      'email': email,
      'signature': signature,
      'avatar_url': avatarUrl,
      'date_created': dateCreated.toIso8601String(),
      'contacts': contacts,
    };
  }

  /// Converts a Map object to a ChatUser2 object.
  static ChatUser fromMap(Map<String, dynamic> map) {
    return ChatUser(
      uid: map['uid'],
      name: map['name'],
      email: map['email'],
      signature: map['signature'] ?? '',
      avatarUrl: map['avatar_url'] ?? '',
      dateCreated: DateTime.parse(map['date_created']),
      contacts: List<String>.from(map['contacts'] ?? []),
    );
  }
}

class ChatUserService{
  ///maybe use Stream? I don't know.

  Future<void> toSupabase(ChatUser user) async {
    await supabaseClient.from('chat_users').insert(user.toMap());
    debugPrint("ChatUser object inserted");
  }

  Future<List> fromSupabase(bool test) async {
    final response = await supabaseClient.from('chat_users').select();
    List<dynamic> jsonArray = jsonDecode(jsonEncode(response));
    List<ChatUser> result = jsonArray.map((e) =>
        ChatUser.fromMap(e)).toList();
    if (test == true) {
      for (var chat in result) {
        debugPrint(chat.name);
        debugPrint(chat.signature);
        debugPrint(chat.avatarUrl);
      }
    }
    return result;
  }

  ChatUser create(
      String name,
      String email,
      String signature,
      String avatarUrl) {
    return ChatUser(
        uid: '',
        name: name,
        email: email,
        signature: signature,
        avatarUrl: avatarUrl,
        dateCreated: DateTime.now(),
        contacts: []);
  }

  Future<void> addToContacts(String currentUserId, String contactUid) async {
    final response = await supabaseClient
        .from('chat_users')
        .select('contacts')
        .eq('uid', currentUserId)
        .single()
        .execute();

    final currentContacts = (response.data['contacts'] as List<dynamic>)
        .map((contact) => contact as String)
        .toList();

    if (!currentContacts.contains(contactUid)) {
      final newContacts = [...currentContacts, contactUid];

      await supabaseClient.from('chat_users').update({
        'contacts': newContacts,
      }).eq('uid', currentUserId).execute();
    }
  }

  Future<void> testInsert() async
  {
    ChatUser alpha = create(
        'Alpha', 'alpha@yahoo.com', '', '');
    await toSupabase(alpha);
    ChatUser beta = create(
        'Beta', 'beta@gmail.com', 'I am a beta male!', 'handsomeman.jpg');
    await toSupabase(beta);
    ChatUser gamma = create(
        'Gamma', 'gamma_man@msn.com', '', 'duck.png');
    await toSupabase(gamma);
  }

  Future<void> testAddContact() async
  {
    var alpha = '0f144230-5d26-4134-a706-c5a3f48f00c0';
    var beta = '01c5bd00-cc53-4bcd-ae22-5fd9f5785f1e';
    var gamma = 'cd0d8407-63ce-43b2-b554-354f6ab51b3b';
    addToContacts(alpha, beta);
    addToContacts(alpha, gamma);
  }

  Stream<List<ChatUser>> getStreamList(bool test) {
    final response = supabaseClient
        .from('chat_users')
        .stream(primaryKey: ['uid'])
        //.order('datecreated')
        .map((maps) =>
        List<Map<String, dynamic>>.from(maps).map((map) =>
            ChatUser.fromMap(map)).toList());
    if (test == true){
      response.listen((data) {
        for (var chat in data) {
          debugPrint(chat.name);
          debugPrint(chat.signature);
          debugPrint(chat.avatarUrl);
        }
      });
    }
    return response;
  }

  ///test that this thing works first before we proceed with coding userDrawer()
  Stream<ChatUser> getStream(String uid, bool test) {
    final response = getStreamList(test);
    return response.map((list) => list.firstWhere((user) => user.uid == uid));
  }

}